version: '3.8'
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenodehad
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HDFS_CONF_dfs_replication=1
      - NAMENODE_RPC_PORT=8020
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    ports:
      - "9871:9870"  # Changed to avoid conflict
      - "8020:8020"
    networks:
      - hadoop

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HDFS_CONF_dfs_replication=1
      - NAMENODE_HOST=namenodehad
      - NAMENODE_RPC_PORT=8020
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - hadoop

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HDFS_CONF_dfs_replication=1
      - NAMENODE_HOST=namenodehad
      - NAMENODE_RPC_PORT=8020
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - hadoop

  spark-master-2c:
    image: gettyimages/spark:2.4.1-hadoop-3.0
    container_name: spark-master-2c
    environment:
      - SPARK_MASTER_HOST=spark-master-2c
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_LOCAL_IP=spark-master-2c
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./spark-config/spark-env-master.sh:/opt/spark/conf/spark-env.sh
    networks:
      - hadoop

  spark-worker1:
    image: gettyimages/spark:2.4.1-hadoop-3.0
    container_name: spark-worker1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1g
      - SPARK_MASTER=spark://spark-master-2c:7077
    command: "bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master-2c:7077"
    depends_on:
      - spark-master-2c
    ports:
      - "8081:8081"
    volumes:
      - ./spark-config/spark-env-worker.sh:/opt/spark/conf/spark-env.sh
    networks:
      - hadoop

  spark-worker2:
    image: gettyimages/spark:2.4.1-hadoop-3.0
    container_name: spark-worker2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1g
      - SPARK_MASTER=spark://spark-master-2c:7077
    command: "bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master-2c:7077"
    depends_on:
      - spark-master-2c
    ports:
      - "8082:8081"
    volumes:
      - ./spark-config/spark-env-worker2.sh:/opt/spark/conf/spark-env.sh
    networks:
      - hadoop

networks:
  hadoop:
    driver: bridge

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
